# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#223249,bg:#1F1F28,preview-bg:#1F1F28 \
--color=fg+:#DCD7BA,fg:#DCD7BA,hl+:#957FB8,hl:#957FB8 \
--color=info:#957FB8,prompt:#98BB6C,pointer:#7AA89F,marker:#E6C384 \
--color=spinner:#658594,header:#98BB6C,border:#727169"