# generated by `theme build` — do not edit
# Sourced by ~/.config/borders/bordersrc to obtain active/inactive colors.
export BORDERS_ACTIVE_COLOR="0xffFFBD5E"
export BORDERS_INACTIVE_COLOR="0xff7B8496"