[meta]
name = "cyberdream"
appearance = "dark"
[palette]
background           = "#16181A"
foreground           = "#FFFFFF"
cursor               = "#FFFFFF"
selection_background = "#3C4048"
selection_foreground = "#FFFFFF"
comment   = "#7B8496"
keyword   = "#FFBD5E"
string    = "#5EFF6C"
function  = "#5EA1FF"
type      = "#BD5EFF"
number    = "#FFBD5E"
variable  = "#FFFFFF"
constant  = "#FF5EA0"
operator  = "#BD5EFF"
property  = "#FFFFFF"
parameter = "#FFFFFF"
error   = "#FF6E5E"
warning = "#F1FF5E"
info    = "#5EA1FF"
hint    = "#5EF1FF"
