# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#3C4048,bg:#16181A,preview-bg:#16181A \
--color=fg+:#FFFFFF,fg:#FFFFFF,hl+:#FFBD5E,hl:#FFBD5E \
--color=info:#FFBD5E,prompt:#5EFF6C,pointer:#BD5EFF,marker:#FFFFFF \
--color=spinner:#5EA1FF,header:#5EFF6C,border:#7B8496"