# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#223249,bg:#181616,preview-bg:#181616 \
--color=fg+:#C5C9C5,fg:#C5C9C5,hl+:#8992A7,hl:#8992A7 \
--color=info:#8992A7,prompt:#8A9A7B,pointer:#8EA4A2,marker:#C4B28A \
--color=spinner:#658594,header:#8A9A7B,border:#737C73"