# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#3a3d37,bg:#252623,preview-bg:#111210 \
--color=fg+:#f1e9d2,fg:#f1e9d2,hl+:#e75a7c,hl:#e75a7c \
--color=info:#aaaaff,prompt:#8fb573,pointer:#dbb651,marker:#70c2be \
--color=spinner:#57a5e5,header:#8fb573,border:#5b5e5a"