# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#3A3D37,bg:#252623,preview-bg:#252623 \
--color=fg+:#F1E9D2,fg:#F1E9D2,hl+:#AAAAFF,hl:#AAAAFF \
--color=info:#AAAAFF,prompt:#8FB573,pointer:#DBB651,marker:#70C2BE \
--color=spinner:#70C2BE,header:#8FB573,border:#E2C792"