require("plugins.manager")

require("plugins.completion")
require("plugins.lsp")
require("plugins.file_tree").setup()
require("plugins.hop")
require("plugins.indent-guides")
require("plugins.telescope")
require("plugins.treesitter").setup()
require("plugins.comment")
require("plugins.transparent")
