require("utils.general")
require("driden.plugins")
require("driden.options").setup()
require("driden.themes").load_theme()
require("driden.keymaps")
require("driden.user_commands").load_commands()
require("driden.highlight")
