# generated by `theme build` — do not edit
# Sourced by ~/.config/borders/bordersrc to obtain active/inactive colors.
export BORDERS_ACTIVE_COLOR="0xff624C83"
export BORDERS_INACTIVE_COLOR="0xff8A8980"