[meta]
name = "kanagawa-lotus"
appearance = "light"
[palette]
background           = "#F2ECBC"
foreground           = "#545464"
cursor               = "#545464"
selection_background = "#C9CBD1"
selection_foreground = "#545464"
comment   = "#8A8980"
keyword   = "#624C83"
string    = "#6F894E"
function  = "#4D699B"
type      = "#597B75"
number    = "#B35B79"
variable  = "#545464"
constant  = "#CC6D00"
operator  = "#836F4A"
property  = "#77713F"
parameter = "#5D57A3"
error   = "#E82424"
warning = "#E98A00"
info    = "#5A7785"
hint    = "#5E857A"
