# generated by `theme build` — do not edit
# Sourced by .zshrc / config.fish. Sets FZF_DEFAULT_OPTS.
export FZF_DEFAULT_OPTS="--layout=reverse --border=rounded \
--color=bg+:#C9CBD1,bg:#F2ECBC,preview-bg:#F2ECBC \
--color=fg+:#545464,fg:#545464,hl+:#624C83,hl:#624C83 \
--color=info:#624C83,prompt:#6F894E,pointer:#597B75,marker:#77713F \
--color=spinner:#5A7785,header:#6F894E,border:#8A8980"