[tools]
go = "latest"
java = "latest"
lua = "5.1"
lua-language-server = "latest"
node = "latest"
opencode = "latest"
ruff = "latest"
uv = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
