[tools]
go = "latest"
java = "latest"
lua = "5.1"
lua-language-server = "latest"
node = "latest"
pi = "latest"
ruff = "latest"
uv = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
bun = "latest"
tree-sitter = "latest"
"npm:typescript-language-server" = "latest"
gh = "latest"
claude-code = "latest"
"pipx:pyright" = "latest"
jq = "latest"
hunk = "latest"
opencode = "latest"
superhtml = "latest"
"npm:@opencode-ai/cli" = { version = "next", allow_builds = ["@opencode-ai/cli"] }
"npm:typescript" = "6"

[settings]
pipx.uvx = true
idiomatic_version_file_enable_tools = [
  "node", "python", "go", "java",
  "ruby", "rust", "terraform", "bun", "deno"]
